### ISSUE TITLE
Got benchmarks?

### ISSUE THREAD

**Issue by alexwal** [gluon-api/gluon-api#12]
Have you released any benchmarks for comparison to other ML frameworks?

Thanks!

**Comment by unnir** [comment]
that would be interesting to see :+1:

**Comment by lupesko** [comment]
Thanks for the suggestion guys. Gluon by itself is just an API. We know that the implementation on top of MXNet is almost as fast and scalable as MXNet symbolic, thanks to Hybridization (and as long as your layers can be hybridized).

I'm closing this issue since this is an implementation question, and not an API spec question.
Feel free to reopen if you think otherwise.
